version: "3.9"

services:
  backend:
    image: maharshi027/naksh-backend:1.0
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env

  frontend:
    image: maharshi027/naksh-frontend:1.0
    ports:
      - "5173:80"
    depends_on:
      - backend
